import assert from 'node:assert/strict'
import { chromium } from '@playwright/test'

const browser = await chromium.launch({ channel: 'chrome', headless: true })
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(process.env.TEST_URL || 'http://127.0.0.1:3001', { waitUntil: 'networkidle' })
  await page.getByRole('combobox', { name: 'Filter by year' }).click()
  await page.getByRole('option', { name: '2025', exact: true }).click()
  assert.ok(await page.locator('.project-year').evaluateAll(nodes => nodes.every(node => node.textContent.trim() === '2025')))
  await page.getByRole('combobox', { name: 'Filter by year' }).click()
  await page.getByRole('option', { name: 'All years', exact: true }).click()
  assert.equal(await page.locator('.project-card').count(), 6)
  const faq = page.getByRole('button', { name: /Not sure what you need yet/ })
  await faq.click()
  assert.equal(await faq.getAttribute('aria-expanded'), 'true')
  await faq.press('Enter')
  assert.equal(await faq.getAttribute('aria-expanded'), 'false')
  await page.getByRole('button', { name: 'Send your message' }).click()
  assert.equal(await page.locator('#name').getAttribute('aria-invalid'), 'true')
  await page.locator('#name').fill('Test User')
  await page.locator('#email').fill('test@example.com')
  await page.locator('#service').selectOption({ label: 'New website' })
  await page.locator('#message').fill('Please build a website for my business.')
  await page.getByRole('checkbox').check()
  await page.route('**/api/contact', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{}' }))
  await page.locator('#email').press('Enter')
  await page.getByRole('alert').waitFor()
  assert.equal(await page.locator('#name').inputValue(), 'Test User')
  await page.unroute('**/api/contact')
  await page.route('**/api/contact', async route => {
    await new Promise(resolve => globalThis.setTimeout(resolve, 300))
    await route.fulfill({ status: 200, contentType: 'application/json', body: '{"ok":true}' })
  })
  await page.getByRole('button', { name: 'Send your message' }).click()
  assert.ok(await page.getByRole('button', { name: /Sending message/ }).isDisabled())
  await page.getByRole('heading', { name: 'Your message is received.' }).waitFor()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => globalThis.window.scrollTo(0, 0))
  const menu = page.getByRole('button', { name: 'Open menu' })
  await menu.click()
  const dialog = page.getByRole('dialog')
  await dialog.waitFor()
  for (let i = 0; i < 8; i++) {
    await page.keyboard.press('Tab')
    assert.ok(await dialog.evaluate(node => node.contains(globalThis.document.activeElement)))
  }
  await page.keyboard.press('Escape')
  await dialog.waitFor({ state: 'hidden' })
  assert.ok(await menu.evaluate(node => node === globalThis.document.activeElement))
  await menu.click()
  await dialog.getByRole('link', { name: /Services/ }).click()
  await dialog.waitFor({ state: 'hidden' })
  assert.ok(page.url().endsWith('#services'))
  assert.ok(await page.evaluate(() => globalThis.document.documentElement.scrollWidth <= globalThis.window.innerWidth))
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  for (const width of [1440, 1024, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 900 })
    for (const selector of ['.hero', '.project-grid', '.contact-grid']) {
      await page.locator(selector).scrollIntoViewIfNeeded()
      assert.ok(await page.evaluate(() => globalThis.document.documentElement.scrollWidth <= globalThis.innerWidth), `Overflow at ${width}: ${selector}`)
    }
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.locator('.project-card').first().click()
  await page.locator('.case-header.motion-enter').waitFor()
  await page.locator('.case-back').click()
  await page.locator('.project-card').first().waitFor()
  await page.locator('.contact-grid').scrollIntoViewIfNeeded()
  await page.locator('.contact-copy.motion-enter').waitFor()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.waitForFunction(() => !globalThis.document.querySelector('.motion-enter'))
  const nojs = await browser.newPage({ javaScriptEnabled: false, viewport: { width: 390, height: 844 } })
  await nojs.goto(process.env.TEST_URL || 'http://127.0.0.1:3001')
  assert.ok(await nojs.locator('.hero h1').isVisible())
  assert.ok(await nojs.locator('.project-card').first().isVisible())
  assert.ok(await nojs.locator('.contact-copy').isVisible())
  await nojs.close()
  globalThis.console.log('Motion: desktop/mobile widths 320–1440, route return, reduced-motion toggle and no-JS content passed')
  assert.deepEqual(errors, [])
  globalThis.console.log('Chrome desktop/mobile: filters, FAQ, form validation/error/loading/success, native submit, Sheet focus/Escape/links and overflow passed')
} finally {
  await browser.close()
}
